const portfolioItems = [
  {
    brand: "portfolio",
    model: "003",
    img: "images/portfolio-webp/003.webp",
    hoverImg: "images/portfolio-webp/003-wire.webp",
    width: 1920,
    height: 1920,
  },
  {
    brand: "portfolio",
    model: "04",
    img: "images/portfolio-webp/04.webp",
    hoverImg: "images/portfolio-webp/04-wire.webp",
    width: 1920,
    height: 1920,
  },
  {
    brand: "andez",
    model: "01",
    img: "images/portfolio-webp/andez-01.webp",
    hoverImg: "images/portfolio-webp/andez-01-wire.webp",
    width: 1535,
    height: 1920,
  },
  {
    brand: "andez",
    model: "02",
    img: "images/portfolio-webp/andez-02.webp",
    hoverImg: "images/portfolio-webp/andez-02-wire.webp",
    width: 1743,
    height: 1920,
  },
  {
    brand: "andez",
    model: "03",
    img: "images/portfolio-webp/andez-03.webp",
    hoverImg: "images/portfolio-webp/andez-03-wire.webp",
    width: 1920,
    height: 1920,
  },
  {
    brand: "andez",
    model: "04",
    img: "images/portfolio-webp/andez-04.webp",
    hoverImg: "images/portfolio-webp/andez-04-wire.webp",
    width: 1547,
    height: 1920,
  },
  {
    brand: "andez",
    model: "05",
    img: "images/portfolio-webp/andez-05.webp",
    hoverImg: "images/portfolio-webp/andez-05-wire.webp",
    width: 1535,
    height: 1920,
  },
  {
    brand: "andez",
    model: "06",
    img: "images/portfolio-webp/andez-06.webp",
    hoverImg: "images/portfolio-webp/andez-06-wire.webp",
    width: 1920,
    height: 1920,
  },
  {
    brand: "andez",
    model: "07",
    img: "images/portfolio-webp/andez-07.webp",
    hoverImg: "images/portfolio-webp/andez-07-wire.webp",
    width: 1535,
    height: 1920,
  },
  {
    brand: "andez",
    model: "10",
    img: "images/portfolio-webp/andez-10.webp",
    hoverImg: "images/portfolio-webp/andez-10-wire.webp",
    width: 1536,
    height: 1920,
  },
  {
    brand: "andez",
    model: "11",
    img: "images/portfolio-webp/andez-11.webp",
    hoverImg: "images/portfolio-webp/andez-11-wire.webp",
    width: 1500,
    height: 1500,
  },
  {
    brand: "andez",
    model: "12",
    img: "images/portfolio-webp/andez-12.webp",
    hoverImg: "images/portfolio-webp/andez-12-wire.webp",
    width: 1080,
    height: 1350,
  },
  {
    brand: "aqua",
    model: "01",
    img: "images/portfolio-webp/aqua-01.webp",
    hoverImg: "images/portfolio-webp/aqua-01-wire.webp",
    width: 1920,
    height: 1363,
  },
  {
    brand: "aqua",
    model: "02",
    img: "images/portfolio-webp/aqua-02.webp",
    hoverImg: "images/portfolio-webp/aqua-02-wire.webp",
    width: 1920,
    height: 1389,
  },
  {
    brand: "aqualaf",
    model: "01",
    img: "images/portfolio-webp/aqualaf-01.webp",
    hoverImg: "images/portfolio-webp/aqualaf-01-wire.webp",
    width: 1533,
    height: 1920,
  },
  {
    brand: "aqualaf",
    model: "02",
    img: "images/portfolio-webp/aqualaf-02.webp",
    hoverImg: "images/portfolio-webp/aqualaf-02-wire.webp",
    width: 1535,
    height: 1920,
  },
  {
    brand: "aqualaf",
    model: "03",
    img: "images/portfolio-webp/aqualaf-03.webp",
    hoverImg: "images/portfolio-webp/aqualaf-03-wire.webp",
    width: 1535,
    height: 1920,
  },
  {
    brand: "aqualaf",
    model: "04",
    img: "images/portfolio-webp/aqualaf-04.webp",
    hoverImg: "images/portfolio-webp/aqualaf-04-wire.webp",
    width: 1535,
    height: 1920,
  },
  {
    brand: "aqualaf",
    model: "05",
    img: "images/portfolio-webp/aqualaf-05.webp",
    hoverImg: "images/portfolio-webp/aqualaf-05-wire.webp",
    width: 1536,
    height: 1920,
  },
  {
    brand: "aqualaf",
    model: "06",
    img: "images/portfolio-webp/aqualaf-06.webp",
    hoverImg: "images/portfolio-webp/aqualaf-06-wire.webp",
    width: 1920,
    height: 1920,
  },
  {
    brand: "aqualaf",
    model: "07",
    img: "images/portfolio-webp/aqualaf-07.webp",
    hoverImg: "images/portfolio-webp/aqualaf-07-wire.webp",
    width: 1920,
    height: 1920,
  },
  {
    brand: "aqualaf",
    model: "09",
    img: "images/portfolio-webp/aqualaf-09.webp",
    hoverImg: "images/portfolio-webp/aqualaf-09-wire.webp",
    width: 1920,
    height: 1363,
  },
  {
    brand: "aqualaf",
    model: "10",
    img: "images/portfolio-webp/aqualaf-10.webp",
    hoverImg: "images/portfolio-webp/aqualaf-10-wire.webp",
    width: 1920,
    height: 1920,
  },
  {
    brand: "aqualaf",
    model: "11",
    img: "images/portfolio-webp/aqualaf-11.webp",
    hoverImg: "images/portfolio-webp/aqualaf-11-wire.webp",
    width: 1920,
    height: 1920,
  },
  {
    brand: "aqualaf",
    model: "12",
    img: "images/portfolio-webp/aqualaf-12.webp",
    hoverImg: "images/portfolio-webp/aqualaf-12-wire.webp",
    width: 1920,
    height: 1363,
  },
  {
    brand: "aqualaf",
    model: "13",
    img: "images/portfolio-webp/aqualaf-13.webp",
    hoverImg: "images/portfolio-webp/aqualaf-13-wire.webp",
    width: 1537,
    height: 1920,
  },
  {
    brand: "aqualaf",
    model: "14",
    img: "images/portfolio-webp/aqualaf-14.webp",
    hoverImg: "images/portfolio-webp/aqualaf-14-wire.webp",
    width: 1536,
    height: 1920,
  },
  {
    brand: "aqualaf",
    model: "15",
    img: "images/portfolio-webp/aqualaf-15.webp",
    hoverImg: "images/portfolio-webp/aqualaf-15-wire.webp",
    width: 1536,
    height: 1920,
  },
];
